apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
spec:
  hostnames:
  - grafana.matoruru.com
  parentRefs:
  - name: common
    namespace: kube-system
  rules:
  - backendRefs:
    - name: prometheus-stack-grafana
      port: 80
    matches:	
    - path:	
        type: PathPrefix	
        value: /
