apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idobata

images:
- name: matoruru_idobata-api
  newName: matoruru/idobata-api
  newTag: 0.0.0-1
- name: matoruru_idobata-ui
  newName: matoruru/idobata-ui
  newTag: 0.0.0-3

resources:
- ./ns.yaml
- ./sa-wi.yaml
- ./secretstore.yaml
- ./api
- ./ui
- ./reload-images
