apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://idobata.vault.azure.net
      serviceAccountRef:
        name: idobata-wi
        namespace: idobata
