apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres.postgres.credentials.postgresql.acid.zalan.do
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: postgres.postgres.credentials.postgresql.acid.zalan.do
  data:
  - secretKey: username
    remoteRef:
      key: secret/engawa-postgresql-postgres-user
  - secretKey: password
    remoteRef:
      key: secret/engawa-postgresql-postgres-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: standby.postgres.credentials.postgresql.acid.zalan.do
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: standby.postgres.credentials.postgresql.acid.zalan.do
  data:
  - secretKey: username
    remoteRef:
      key: secret/engawa-postgresql-standby-user
  - secretKey: password
    remoteRef:
      key: secret/engawa-postgresql-standby-password
