apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-api
spec:
  hostnames:
  - engawa-api.matoruru.com
  parentRefs:
  - kind: Gateway
    name: common
    namespace: kube-system
  rules:
  - backendRefs:
    - name: api
      port: 8080
