apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ui-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: ui-secret
  data:
  - secretKey: VITE_WS_URL
    remoteRef:
      key: secret/engawa-ui-ws-url
  - secretKey: VITE_API_URL
    remoteRef:
      key: secret/engawa-ui-api-url
