apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reload-images
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - api
  - ui
  verbs:
  - get
  - patch
