apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
spec:
  hostnames:
  - postgres-operator.matoruru.com
  parentRefs:
  - name: common
    namespace: kube-system
  rules:
  - backendRefs:
    - name: postgres-operator-ui
      port: 8001
    matches:	
    - path:	
        type: PathPrefix	
        value: /
