
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reload-images-role-binding
subjects:
- kind: ServiceAccount
  name: reload-images
roleRef:
  kind: Role
  name: reload-images
  apiGroup: rbac.authorization.k8s.io
