apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-ui
spec:
  hostnames:
  - idobata.matoruru.com
  parentRefs:
  - kind: Gateway
    name: common
    namespace: kube-system
  rules:
  - backendRefs:
    - name: ui
      port: 8080
