apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: idobata
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 4173
  selector:
    app: idobata
  type: ClusterIP
