apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: engawa

images:
- name: matoruru_engawa-api
  newName: matoruru/engawa-api
  newTag: 0.0.0-4
- name: matoruru_engawa-ui
  newName: matoruru/engawa-ui
  newTag: 0.0.0-6

resources:
- ./ns.yaml
- ./sa-wi.yaml
- ./secretstore.yaml
- ./api
- ./ui
- ./reload-images
