apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://engawa.vault.azure.net
      serviceAccountRef:
        name: engawa-wi
        namespace: engawa
